require('dotenv').config();
const { Telegraf } = require('telegraf');
const ytSearch = require('yt-search');
const axios = require('axios');
const fs = require('fs');

if (!process.env.BOT_TOKEN) throw new Error('BOT_TOKEN မရှိပါ!');
const bot = new Telegraf(process.env.BOT_TOKEN);

// မှတ်တမ်းသိမ်းရန် (Memory ထဲတွင် ယာယီသိမ်းဆည်းမည်)
const userHistory = new Map();

// JWT Token မလိုသော လွတ်လပ်သည့် Cobalt ဆာဗာများ စာရင်း
const COBALT_INSTANCES = [
    'https://cobalt.canine.ly',
        'https://co.eepy.today',
            'https://cobalt.cachyos.org',
                'https://cobalt.starnix.network'
                ];

                bot.start((ctx) => ctx.reply('🎵 Music Bot မှ ကြိုဆိုပါတယ်။\nသီချင်းရှာရန်: /play သီချင်းနာမည် ဟု ရိုက်ထည့်ပါ။\nမှတ်တမ်းကြည့်ရန်: /recent ဟုရိုက်ထည့်ပါ။'));

                // မကြာသေးမီက သီချင်းမှတ်တမ်းကြည့်ရန် Command
                bot.command('recent', (ctx) => {
                    const userId = ctx.from.id;
                        const history = userHistory.get(userId);

                            if (!history || history.length === 0) {
                                    return ctx.reply('📭 မကြာသေးမီက နားထောင်ထားသော သီချင်းမှတ်တမ်း မရှိသေးပါဘူးဗျ။\n/play ဖြင့် သီချင်းအရင်ရှာပါ။');
                                        }

                                            let message = '🕒 <b>မကြာသေးမီက နားထောင်ခဲ့သော သီချင်းများ:</b>\n\n';
                                                history.forEach((song, index) => {
                                                        message += `${index + 1}. <b>${song.title}</b>\n`;
                                                            });

                                                                ctx.reply(message, { parse_mode: 'HTML' });
                                                                });

                                                                bot.command('play', async (ctx) => {
                                                                    const query = ctx.message.text.split(' ').slice(1).join(' ');
                                                                        if (!query) return ctx.reply('ကျေးဇူးပြု၍ သီချင်းနာမည် ရိုက်ထည့်ပါ။ ဥပမာ: /play perfect');

                                                                            const waitMsg = await ctx.reply('🔍 သီချင်းရှာနေပါတယ်... ခဏစောင့်ပါဗျ။');

                                                                                try {
                                                                                        // ၁။ YouTube မှ Video ရှာခြင်း
                                                                                                const ytResult = await ytSearch(query);
                                                                                                        const video = ytResult.videos.length > 0 ? ytResult.videos[0] : null;

                                                                                                                if (!video) {
                                                                                                                            return ctx.telegram.editMessageText(ctx.chat.id, waitMsg.message_id, undefined, '❌ သီချင်းရှာမတွေ့ပါဘူးဗျ။');
                                                                                                                                    }

                                                                                                                                            await ctx.telegram.editMessageText(ctx.chat.id, waitMsg.message_id, undefined, `🎧 <b>${video.title}</b> ကို ရှာဖွေရရှိပါပြီ... Link ချိတ်ဆက်နေပါသည်`, { parse_mode: 'HTML' });

                                                                                                                                                    // သီချင်းမှတ်တမ်း (History) ထဲသို့ ထည့်ခြင်း
                                                                                                                                                            const userId = ctx.from.id;
                                                                                                                                                                    if (!userHistory.has(userId)) {
                                                                                                                                                                                userHistory.set(userId, []);
                                                                                                                                                                                        }
                                                                                                                                                                                                const history = userHistory.get(userId);
                                                                                                                                                                                                        
                                                                                                                                                                                                                // သီချင်းအသစ်ကို ထိပ်ဆုံးမှထည့်မည် (တူညီတဲ့သီချင်းပါပြီးသားဆိုရင် အဟောင်းကိုဖျက်မယ်)
                                                                                                                                                                                                                        const existingIndex = history.findIndex(s => s.url === video.url);
                                                                                                                                                                                                                                if (existingIndex !== -1) history.splice(existingIndex, 1);
                                                                                                                                                                                                                                        history.unshift({ title: video.title, url: video.url });
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                        // နောက်ဆုံး (၁၀) ပုဒ်သာ မှတ်ထားမည်
                                                                                                                                                                                                                                                                if (history.length > 10) history.pop();

                                                                                                                                                                                                                                                                        // ၂။ Community Cobalt ဆာဗာများမှတစ်ဆင့် Audio Link တောင်းယူခြင်း
                                                                                                                                                                                                                                                                                let audioUrl = null;
                                                                                                                                                                                                                                                                                        for (const instance of COBALT_INSTANCES) {
                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                    const res = await axios.post(instance, {
                                                                                                                                                                                                                                                                                                                                        url: video.url,
                                                                                                                                                                                                                                                                                                                                                            downloadMode: 'audio',
                                                                                                                                                                                                                                                                                                                                                                                audioFormat: 'mp3'
                                                                                                                                                                                                                                                                                                                                                                                                }, {
                                                                                                                                                                                                                                                                                                                                                                                                                    headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                            'Accept': 'application/json',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Content-Type': 'application/json'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            timeout: 10000 // ၁၀ စက္ကန့်စောင့်မည်
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (res.data && res.data.url) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                audioUrl = res.data.url;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break; // Link ရလျှင် ဆာဗာရှာခြင်းကို ရပ်မည်
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                continue; // Error တက်လျှင် နောက်ဆာဗာတစ်ခုသို့ ပြောင်းမည်
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!audioUrl) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        throw new Error("ဆာဗာများအားလုံး ကျနေပါသည်။");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await ctx.telegram.editMessageText(ctx.chat.id, waitMsg.message_id, undefined, `📥 သီချင်းဖိုင်ကို ဒေါင်းလုဒ်ဆွဲနေပါသည်...`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ၃။ ရလာသော Link မှတစ်ဆင့် MP3 ဖိုင်ကို Bot ထဲသို့ ဆွဲချခြင်း
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const fileName = `./${Date.now()}.mp3`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const response = await axios({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            method: 'GET',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        url: audioUrl,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    responseType: 'stream'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const writer = fs.createWriteStream(fileName);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            response.data.pipe(writer);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await new Promise((resolve, reject) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                writer.on('finish', resolve);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            writer.on('error', reject);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await ctx.telegram.editMessageText(ctx.chat.id, waitMsg.message_id, undefined, `📤 Telegram သို့ ပို့နေပါပြီ...`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // ၄။ Telegram သို့ ပို့ဆောင်ခြင်း
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await ctx.replyWithAudio({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        source: fileName
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title: video.title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        performer: video.author.name
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ၅။ ပို့ပြီးတာနဲ့ ဖိုင်ကို ပြန်ဖျက်ခြင်း
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (fs.existsSync(fileName)) fs.unlinkSync(fileName);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await ctx.telegram.deleteMessage(ctx.chat.id, waitMsg.message_id);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error("Music Error:", error.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ctx.telegram.editMessageText(ctx.chat.id, waitMsg.message_id, undefined, '❌ အမှားအယွင်းဖြစ်သွားပါသည်။ အခြားသီချင်းခေါင်းစဉ်ဖြင့် ပြန်လည်စမ်းသပ်ကြည့်ပါ။');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bot.launch().then(() => console.log('Music Bot is running via Community Cobalt...')).catch(err => console.error(err));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                